name: Deploy python images

on:
  workflow_dispatch:

jobs:
  base27:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-base
          dockerfile: py-base/Dockerfile_27
          repository: riga/py-base
          tags: 2.7,2
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  sci27:
    needs: base27
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-sci
          dockerfile: py-sci/Dockerfile_27
          repository: riga/py-sci
          tags: 2.7,2
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  ml27:
    needs: sci27
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-ml
          dockerfile: py-ml/Dockerfile_27
          repository: riga/py-ml
          tags: 2.7,2
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  base37:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-base
          dockerfile: py-base/Dockerfile_37
          repository: riga/py-base
          tags: 3.7
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  sci37:
    needs: base37
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-sci
          dockerfile: py-sci/Dockerfile_37
          repository: riga/py-sci
          tags: 3.7
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  ml37:
    needs: sci37
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-ml
          dockerfile: py-ml/Dockerfile_37
          repository: riga/py-ml
          tags: 3.7
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  base38:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-base
          dockerfile: py-base/Dockerfile_38
          repository: riga/py-base
          tags: 3.8,3,latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  sci38:
    needs: base38
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-sci
          dockerfile: py-sci/Dockerfile_38
          repository: riga/py-sci
          tags: 3.8,3,latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  ml38:
    needs: sci38
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-ml
          dockerfile: py-ml/Dockerfile_38
          repository: riga/py-ml
          tags: 3.8
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  base39:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-base
          dockerfile: py-base/Dockerfile_39
          repository: riga/py-base
          tags: 3.9
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  sci39:
    needs: base39
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-sci
          dockerfile: py-sci/Dockerfile_39
          repository: riga/py-sci
          tags: 3.9
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  ml39:
    needs: sci39
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build and deploy image ğŸ³
        uses: docker/build-push-action@v1
        with:
          path: py-ml
          dockerfile: py-ml/Dockerfile_39
          repository: riga/py-ml
          tags: 3.9,3,latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
